config/routes.rb
Rails.application.routes.draw do

  resource :session, only: [:create, :destroy, :new]

  resources :users, only: [:create, :new, :show] do
    get :activate, on: :collection
  end

  resources :bands do
    resources :albums, only: :new
  end

  resources :albums, except: [:index, :new] do
    resources :tracks, only: :new
  end

  resources :tracks, except: [:index, :new]

  resources :notes, only: [:create, :destroy]

  root to: redirect("/bands")

end

app/models/track.rb
# == Schema Information
#
# Table name: tracks
#
#  id         :integer          not null, primary key
#  album_id   :integer          not null
#  bonus      :boolean          default(FALSE)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Track < ActiveRecord::Base

  belongs_to :album

  has_one :band,
    through: :album,
    source: :band

  has_many :notes, dependent: :destroy

  validates(
    :album,
    :title,
    :ord,
    presence: :true
  )

  validates :bonus, inclusion: { in: [true, false] }
  validates :ord, uniqueness: { scope: :album_id }

end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :require_log_in!

  def create
    @track = Track.new(track_params)

    if @track.save
      redirect_to track_url(@track)
    else
      @album = @track.album
      render :new
    end
  end

  def destroy
    @track = Track.find(params[:id])
    @track.destroy
    redirect_to album_url(@track.album_id)
  end

  def edit
    @track = Track.find(params[:id])
    render :edit
  end

  def new
    @album = Album.find(params[:album_id])
    @track = Track.new(album_id: params[:album_id])
    render :new
  end

  def show
    @track = Track.find(params[:id])
    render :show
  end

  def update
    @track = Track.find(params[:id])
    if @track.update(track_params)
      redirect_to track_url(@track)
    else
      render :edit
    end
  end

  private
  def track_params
    params.require(:track).permit(:album_id, :bonus, :lyrics, :title, :ord)
  end
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/views/tracks/_form.html.erb
<% action_url = track.persisted? ? track_url(track) : tracks_url %>
<% http_method = track.persisted? ? "PATCH" : "POST" %>


<% if !track.errors.full_messages.empty? %>
<ul>
  <% track.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
  <% end %>
</ul>
<% end %>

<form action="<%= action_url %>" method="POST" %>
  <input type="hidden" name="_method" value="<%= http_method %>">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <input type="text" name="track[title]" value="<%= track.title %>">
  <br>

<label>Album
  <select name="track[album_id]">
    <% Album.all.each do |album| %>
      <option
        <%= "selected" if track.album_id == album.id %>
        value="<%= album.id %>">
          <%= album.title %>
      </option>
    <% end %>
  </select>
</label>
<br>

  <input type="number" name="track[ord]" value="<%= track.ord %>">
  <br>

  <input
    type="radio"
    name="track[bonus]"
    value="f"
    id="track_bonus_f"
    <%= "checked" if !track.bonus %>>
  <label for="track_bonus_f">Standard</label>
  <br>
  <input
    type="radio"
    name="track[bonus]"
    value="t"
    id="track_bonus_t"
    <%= "checked" if track.bonus %>>
  <label for="track_bonus_t">Bonus</label>
  <br>

  <label for="track_lyrics">Lyrics</label>
  <textarea id="track_lyrics" name="track[lyrics]"><%= track.lyrics %></textarea>
  <br>

  <input type="submit">
</form>

app/views/tracks/edit.html.erb
<h1>Edit <%= @track.title %></h1>

<%= render "form", track: @track %>

app/views/tracks/new.html.erb
<h1>New <%= @album.title %> Track</h1>

<%= render "form", track: @track %>

app/views/tracks/show.html.erb
<h1><%= @track.title %></h1>

<%= ugly_lyrics(@track.lyrics) %>

<% @track.notes.each do |note| %>
  <%= render "note/note", note: note %>
<% end %>

<%= render "note/form", track: @track %>

<h4>Links</h4>
<ul>
  <li><%= link_to "Edit Track", edit_track_url(@track) %></li>
  <li><%= link_to "Delete Track", track_url(@track), method: :delete %></li>
  <li><%= link_to @track.album.name, album_url(@track.album) %></li>
</ul>