config/routes.rb
Rails.application.routes.draw do

  resource :session, only: [:create, :destroy, :new]

  resources :users, only: [:create, :new, :show] do
    get :activate, on: :collection
  end

  resources :bands do
    resources :albums, only: :new
  end

  resources :albums, except: [:index, :new] do
    resources :tracks, only: :new
  end

  resources :tracks, except: [:index, :new]

  resources :notes, only: [:create, :destroy]

  root to: redirect("/bands")

end

app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id         :integer          not null, primary key
#  band_id    :integer          not null
#  set        :string           default("studio")
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Album < ActiveRecord::Base
  ALBUM_SETS = ["live", "studio"]

  belongs_to :band
  has_many :tracks, dependent: :destroy

  validates(
    :band,
    :year,
    :title,
    :band_id,
    :set,
    presence: true)

  validates :set, inclusion: ALBUM_SETS
  validates :title, uniqueness: { scope: :band_id }
  validates :year, numericality: { minimum: 1000 }


end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  before_action :require_log_in!

  def create
    @album = Album.new(album_params)

    if @album.save
      redirect_to album_url(@album)
    else
      flash.now[:errors] = @album.errors.full_messages
      @band = @album.band
      render :new
    end
  end

  def new
    @album = Album.new(band_id: params[:band_id])
    @band = Band.find(params[:band_id])
    render :new
  end

  def edit
    @bands = Band.all
    @album = Album.find(params[:id])
    render :edit
  end

  def show
    @album = Album.find(params[:id])
    render :show
  end

  def update
    @album = Album.find(params[:id])
    if @album.update_attributes(album_params)
      redirect_to album_url(@album)
    else
      flash.now[:errors] = @album.errors.full_messages
      render :edit
    end
  end

  def destroy
    @album = Album.find_by(params[:id])
    @album.destroy
    redirect_to band_url(@album.band_id)
  end

  private
  def album_params
    params.require(:album).permit(:title, :band_id, :set, :year)
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/_form.html.erb
<% action = (album.persisted? ? album_url(album) : albums_url) %>
<% method = (album.persisted? ? :patch : :post) %>

<% if album.persisted? %>
  <%= button_to "<- Album Page", album_url(album), method: :get %>
<% end %>

<br><br>

<form action="<%= action %>" method="post">
  <input type="hidden" name="_method" value="<%= method %>">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <label for="album_title">Album Title:</label>
  <input
    type="text"
    name="album[title]"
    id="album_title"
    value="<%= album.title %>">

  <br>

  <label for="album_year">Album Year:</label>
  <input
    type="integer"
    name="album[year]"
    id="album_year"
    value="<%= album.year %>">
  <br><br>

  <label for="album_band">Band:</label>
  <select name="album[band_id]" id="album_band">
    <option></option>
    <% Band.all.each do |band| %>
      <option
        <%= album.band_id == band.id ? "selected" : "" %>
        value="<%= band.id %>">
        <%= band.name %>
      </option>
    <% end %>
  </select>

  <br><br>


  <% Album::ALBUM_SETS.each do |set| %>
    <label for="album_set"><%= set %></label>
    <input type="radio"
      name="album[set]" id="album_set"
      value="<%= set %>"
      <%= "checked" if  album.set == set  %>
    >
  <% end %>

  <br><br>

  <% if album.persisted? %>
  <label for="trackslist">TRACKS</label>
    <table id="trackslist">
      <tr>
        <th>#</th>
        <th>Song</th>
        <th>Length</th>
        <th>type</th>
      </tr>

        <% @album.tracks.each_with_index do |track, i| %>
          <tr>
            <%= render "track_tr", track: track, num: i %>
            <td><%= button_to "edit", edit_track_url(track.id), method: :get %></td>
          </tr>
        <% end %>

    </table>
    <%= button_to "Add Track", new_album_track_url(album.id) %>
  <% end %>

  <br>

  <% submit_text = (album.persisted? ? 'Update' : 'Add') + ' Album' %>
  <input type="submit" value="<%= submit_text %>">
</form>

app/views/albums/_track_tr.html.erb
<td><%= num %></td>
<td><%= track.title %></td>
<td>5:00</td>
<td><%= track.bonus if track.bonus %></td>

app/views/albums/edit.html.erb
<h1>Edit Album</h1>
<%= render "shared/errors" %>
<%= render "form", album: @album %>

app/views/albums/new.html.erb
<h1>New Album</h1>
<%= render "shared/errors" %>
<%= render "form", album: @album %>

app/views/albums/show.html.erb
<h1><%= @album.title %></h1>
band: <%= @album.band.name %>

<br><br>

<label for="trackslist">TRACKS</label>
<table id="trackslist">
  <tr>
    <th>#</th>
    <th>Song</th>
    <th>Length</th>
    <th>type</th>
  </tr>
    <% @album.tracks.each do |track| %>
      <tr>
        <td><%= track.ord %></td>
        <td><%= link_to track.title, track_url(track) %></td>
        <td>5:00</td>
        <td><%= track.bonus if track.bonus %></td>
    </tr>
    <% end %>
</table>

<h4>Links</h4>
<ul>
  <li><%= link_to "add new track", new_album_track_url(@album) %></li>
  <li><%= link_to "Edit Album", edit_album_url(@album) %></li>
  <li><%= link_to "Delete Album!", album_url(@album), method: :delete %></li>
  <li><%= link_to @album.band.name, band_url(@album.band) %></li>
</ul>