config/routes.rb
Rails.application.routes.draw do

  resource :session, only: [:create, :destroy, :new]

  resources :users, only: [:create, :new, :show] do
    get :activate, on: :collection
  end

  resources :bands do
    resources :albums, only: :new
  end

  resources :albums, except: [:index, :new] do
    resources :tracks, only: :new
  end

  resources :tracks, except: [:index, :new]

  resources :notes, only: [:create, :destroy]

  root to: redirect("/bands")

end

app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :integer          not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Band < ActiveRecord::Base

  has_many :albums, dependent: :destroy

  validates :name, presence: true, uniqueness: true


end

app/controllers/bands_controller.rb
class BandsController < ApplicationController

  before_action :require_log_in!

  def index
    @bands = Band.all
    render :index
  end

  def create
    @band = Band.new(band_params)

    if @band.save
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :new
    end
  end

  def new
    @band = Band.new
    render :new
  end

  def edit
    @band = Band.find(params[:id])
    render :edit
  end

  def show
    @band = Band.find(params[:id])
    render :show
  end

  def update
    @band = Band.find(params[:id])
    if @band.update(band_params)
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :edit
    end
  end

  def destroy
    @band = Band.find(params[:id])
    @band.destroy
    redirect_to bands_url
  end

  private
  def band_params
    params.require(:band).permit(:name)
  end
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/views/bands/_form.html.erb
<% action = (band.persisted? ? band_url(band) : bands_url) %>
<% method = (band.persisted? ? :patch : :post) %>

<% if band.persisted? %>
  <%= button_to "<- Band Page", band_url(band), method: :get %>
<% end %>

<br><br>

<form action="<%= action %>" method="post">
  <input type="hidden" name="_method" value="<%= method %>">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <input
    type="text"
    name="band[name]"
    id="band_name"
    value="<%= band.name %>">

  <% submit_text = (band.persisted? ? 'Update' : 'Create') + ' Band Name' %>
  <input type="submit" value="<%= submit_text %>">
</form>


<br>
<% if band.persisted? %>
  <%= button_to "Add Album", new_band_album_url(band), {band_id: band.id, method: :get} %>
<% end %>

app/views/bands/edit.html.erb
<h1>Edit Band</h1>
<%= render "shared/errors" %>
<%= render "form", band: @band %>
<%= button_to "Delete Band", band_url(@band), method: :delete %>

app/views/bands/index.html.erb
<h1>Bands</h1>

<ul>
  <% @bands.each do |band| %>
    <li><%= link_to band.name, band_url(band) %></li>
  <% end %>
</ul>
<br><br>
<%= link_to "Add Band!", new_band_url %>

app/views/bands/new.html.erb
<h1>New Band</h1>

<%= render "form", band: @band %>

app/views/bands/show.html.erb
<h1><%= @band.name %></h1>

<table>
  <tr>
    <th>Albums</th>
    <th>Time Added</th>
  </tr>
  <% @band.albums.each do |album| %>
    <tr>
      <td><li><%= link_to album.title, album_url(album.id) %></li></td>
      <td><%= album.created_at %></td>
    </tr>
  <% end %>
</table>
<br><br>
<%= link_to "back to bands", bands_url %>
<%= link_to "Edit Band", edit_band_url(@band) %>